# Generated by Django 4.0.6 on 2022-07-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Abuelo',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Primo',
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Tio',
        ),
        migrations.RenameField(
            model_name='abuelo',
            old_name='camada',
            new_name='comision',
        ),
    ]
